### ISSUE TITLE
I got an error "the Credential is mal-formed"

### ISSUE THREAD

**Issue by arsis1** [hubrick/vertx-s3-client#13]
Thanks for providing a very nice client for aws s3.
I am trying to upload a file to s3 as below. 
But I got "the Credential is mal-formed" error.

My code is 
```
                final OpenOptions openOptions = new OpenOptions().setRead(true);
		vertx.fileSystem().open(file, openOptions, asyncFile -> {
			// publish file
			this.s3Client.adaptiveUpload(
                bucket,
                "someid", // TODO
                new AdaptiveUploadRequest(asyncFile.result()).withContentType("video/mp4"),
                success -> {
                	log.info(file + " publish success");
                	future.complete();
                },
                fail -> {
                	log.error(file + " publish fail", fail);
                	future.fail(file);
                }
            );
        });
```
Belows are logs.
```
12:48:32.883 [vert.x-eventloop-thread-1] INFO  c.w.v.publisher.base.Executor - input :
{
  "bucket" : "temp-scenappsm",
  "secretKey" : "Z*****************************",
  "accessKey" : "A*******************",
  "files" : [ "/nfs_test/a.mp4" ],
  "region" : "ap-northeast-2",
  "serviceName" : "s3"
}
12:48:33.312 [vert.x-eventloop-thread-1] INFO  c.w.v.publisher.base.Publisher - resource : /nfs_test/a.mp4
12:48:33.314 [vert.x-eventloop-thread-1] INFO  c.w.v.publisher.base.Publisher - uploading : /nfs_test/a.mp4
12:48:33.579 [vert.x-eventloop-thread-1] INFO  c.h.v.s3.client.S3ClientRequest - S3 toSign:
POST
/temp-scenappsm/someid
uploads=
content-type:video/mp4
host:s3-ap-northeast-2.amazonaws.com
x-amz-date:20171102T034833Z

content-type;host;x-amz-date
UNSIGNED-PAYLOAD
12:48:33.645 [vert.x-eventloop-thread-1] DEBUG i.netty.channel.DefaultChannelId - -Dio.netty.processId: 6015 (auto-detected)
12:48:33.648 [vert.x-eventloop-thread-1] DEBUG i.netty.channel.DefaultChannelId - -Dio.netty.machineId: e4:11:5b:ff:fe:de:04:88 (auto-detected)
12:48:33.729 [vert.x-eventloop-thread-1] DEBUG i.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@681ab20f
12:48:33.730 [vert.x-eventloop-thread-1] DEBUG i.n.resolver.dns.DnsQueryContext - [id: 0x48e8982e] WRITE: [5271: /210.220.163.82:53], DefaultDnsQuestion(s3-ap-northeast-2.amazonaws.com. IN A)
12:48:33.746 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
12:48:33.746 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
12:48:33.746 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
12:48:33.746 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
12:48:33.761 [vert.x-eventloop-thread-1] DEBUG i.n.resolver.dns.DnsQueryContext - [id: 0x48e8982e] WRITE: [38247: /210.220.163.82:53], DefaultDnsQuestion(s3-ap-northeast-2.amazonaws.com. IN AAAA)
12:48:33.762 [vert.x-eventloop-thread-1] DEBUG c.h.v.s3.client.S3ClientRequest - Request Body:
12:48:33.772 [vert.x-eventloop-thread-1] DEBUG i.n.resolver.dns.DnsNameResolver - [id: 0x48e8982e] RECEIVED: [5271: /210.220.163.82:53], DatagramDnsResponse(from: /210.220.163.82:53, to: /0:0:0:0:0:0:0:0:54549, 5271, QUERY(0), NoError(0), RD RA)
        DefaultDnsQuestion(s3-ap-northeast-2.amazonaws.com. IN A)
        DefaultDnsRawRecord(s3-ap-northeast-2.amazonaws.com. 415 IN CNAME 20B)
        DefaultDnsRawRecord(s3.ap-northeast-2.amazonaws.com. 5 IN A 4B)
        DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
12:48:33.778 [vert.x-eventloop-thread-1] DEBUG i.n.resolver.dns.DnsNameResolver - [id: 0x48e8982e] RECEIVED: [38247: /210.220.163.82:53], DatagramDnsResponse(from: /210.220.163.82:53, to: /0:0:0:0:0:0:0:0:54549, 38247, QUERY(0), NoError(0), RD RA)
        DefaultDnsQuestion(s3-ap-northeast-2.amazonaws.com. IN AAAA)
        DefaultDnsRawRecord(s3-ap-northeast-2.amazonaws.com. 415 IN CNAME 20B)
        DefaultDnsRawRecord(s3.ap-northeast-2.amazonaws.com. 900 IN SOA 72B)
        DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
12:48:33.826 [vert.x-eventloop-thread-1] WARN  c.h.vertx.s3.client.S3Client - Error occurred. Status: 400, Message: Bad Request
12:48:33.826 [vert.x-eventloop-thread-1] INFO  c.h.vertx.s3.client.S3Client - Response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the Credential is mal-formed; expecting "&lt;YOUR-AKID&gt;/YYYYMMDD/REGION/SERVICE/aws4_request".</Message><RequestId>17354AE5A6A73B50</RequestId><HostId>hnBxTmNhqvlBDTgif7pULLkFA4YZYVmjdDP6QchZDx48dH+v0/912MYZFo12Ub8weFObyZUCONk=</HostId></Error>
12:48:33.833 [vert.x-eventloop-thread-1] ERROR c.w.v.publisher.impl.S3Publisher - /nfs_test/a.mp4 publish fail
com.hubrick.vertx.s3.exception.HttpErrorException: Error occurred on 'initMultipartUpload'
        at com.hubrick.vertx.s3.client.S3Client$XmlBodyResponseHandler.lambda$handle$0(S3Client.java:1249)
        at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:307)
        at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:197)
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:261)
        at io.vertx.core.http.impl.ClientConnection.handleResponseEnd(ClientConnection.java:358)
        at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:100)
        at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:36)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
12:48:33.834 [vert.x-eventloop-thread-1] ERROR c.w.v.publisher.impl.S3Publisher - null publish failed
```

**Comment by marcust** [comment]
@arsis1 First of all, please revoke your keypair for AWS, which you posted in the debug output. We will have a look at this in detail later.

**Comment by arsis1** [comment]
Thanks marcust, I just inactivated the key.

**Comment by eemmiirr** [comment]
@arsis1 Can you please provide your s3 client configuration in java

**Comment by arsis1** [comment]
My s3 client configuration is ...

I found my problem. Thanks eemmiirr.
I typed in secret key in setAwsAccessKey() and access key in setAwsSecretKey().

I close.
